//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class appinfo : global::System.Configuration.ApplicationSettingsBase {
        
        private static appinfo defaultInstance = ((appinfo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appinfo())));
        
        public static appinfo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int teTabIndent {
            get {
                return ((int)(this["teTabIndent"]));
            }
            set {
                this["teTabIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 10pt")]
        public global::System.Drawing.Font teFont {
            get {
                return ((global::System.Drawing.Font)(this["teFont"]));
            }
            set {
                this["teFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 10pt")]
        public global::System.Drawing.Font shFont {
            get {
                return ((global::System.Drawing.Font)(this["shFont"]));
            }
            set {
                this["shFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color shKeyword {
            get {
                return ((global::System.Drawing.Color)(this["shKeyword"]));
            }
            set {
                this["shKeyword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkCyan")]
        public global::System.Drawing.Color shType {
            get {
                return ((global::System.Drawing.Color)(this["shType"]));
            }
            set {
                this["shType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color shComment {
            get {
                return ((global::System.Drawing.Color)(this["shComment"]));
            }
            set {
                this["shComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brown")]
        public global::System.Drawing.Color shString {
            get {
                return ((global::System.Drawing.Color)(this["shString"]));
            }
            set {
                this["shString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int teDefFileExt {
            get {
                return ((int)(this["teDefFileExt"]));
            }
            set {
                this["teDefFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int shDefFileExt {
            get {
                return ((int)(this["shDefFileExt"]));
            }
            set {
                this["shDefFileExt"] = value;
            }
        }
    }
}
